# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e851817b29c2284bc4d4cd28d19b780fcb5ee26bf7d1208fb045531d1acc21df24f04cec2cac51776dd54c1738cc5b705c759add591b65a5e4b5b1077ed8b68

test:
  secret_key_base: b3e63dd3b645b0cd7fb20bf23fdd615aee1230bdf2992114f6ae59d6da5181a03fea3056df0a3938e5b563358a679f871ff740e620a4fd9dc9d50a0baa98d89e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
